metadata:
  name: darja_deals
  class: project
  type: board
  version: "2.0"
freshness:
  sync_status: fresh
  sync_count: 0
  last_synced: '2026-07-04T02:36:52.162956Z'
  last_edited: '2026-07-04'
  fill_queue:
    os_prompts: []
    ledgers: []
    missions: []
    pipelines: []
    toolboxes: []
control:
  status: true
  auto_mode: false
  plan_first: off
  pipelines_control:
    local_pipelines: off
    shared_pipelines: off
  toolboxes_control:
    local_toolboxes: off
    shared_toolboxes: off
  boot: on
  sync_daemon: on
  evolution:
    status: off
metrics:
  os_prompts: 1
  ledgers:
    total: 0
    indexed: 0
  missions_metrics:
    total: 0
    active: 0
    paused: 0
    completed: 0
    archived: 0
    unlimited_missions: 0
    missions_progress_percentage: 0
    missions_current_round_progress_percentage: 0
  pipelines_metrics:
    etrics:
    total: 2
    local: 0
    shared: 2
    active_pipelines:
      local: 0
      shared: 0
      total: 0
      stub: 0
      functional: 0
      hardened: 0
      battle-tested: 0
    inactive_pipelines:
      local: 0
      shared: 2
      total: 2
      stub: 2
      functional: 0
      hardened: 0
      battle-tested: 0
  toolboxes_metrics:
    total: 72
    local: 0
    shared: 72
    active_toolboxes:
      local: 0
      shared: 0
      total: 0
      stub: 0
      functional: 0
      hardened: 0
      battle-tested: 0
    inactive_toolboxes:
      local: 0
      shared: 72
      total: 72
      stub: 0
      functional: 0
      hardened: 0
      battle-tested: 0
state:
  last_progress_at: ''
  recent_events: []
  review_queue: []
  backlog: []
  evolution: {}
missions: {}
pipelines:
  pipelines_metrics:
    local_pipelines:
      total: 0
      active_pipelines:
        total: 0
        stub: 0
        functional: 0
        hardened: 0
        battle-tested: 0
      inactive_pipelines:
        total: 0
        stub: 0
        functional: 0
        hardened: 0
        battle-tested: 0
    shared_pipelines:
      total: 2
      active_pipelines:
        total: 0
        stub: 0
        functional: 0
        hardened: 0
        battle-tested: 0
      inactive_pipelines:
        total: 2
        stub: 2
        functional: 0
        hardened: 0
        battle-tested: 0
  hustler:
    last_progress_at: ''
    definition_source: shared
    pipeline_control:
      status: off
      maturity: stub
    pipeline_metrics:
      active_pillars: 0
      INTERNAL:
        PLANNING_runs:
          total: 0
          need_aproval: 0
          active: 0
        EXECUTION_runs:
          total: 0
          need_aproval: 0
          active: 0
      INBOX:
        PLANNING_runs:
          total: 0
          need_aproval: 0
          active: 0
        EXECUTION_runs:
          total: 0
          need_aproval: 0
          active: 0
      RESEARCH:
        PLANNING_runs:
          total: 0
          need_aproval: 0
          active: 0
        EXECUTION_runs:
          total: 0
          need_aproval: 0
          active: 0
    pipeline_state:
      recent_events: []
      review_queue: []
      backlog: []
    pillars:
      user_added:
        pillars: []
      agents_added:
        pillars: []
      active_pillars: []
    profiles:
      INTERNAL:
        status: off
        runs:
          PLANNING:
            status: off
            focused_pillars: all
            focused_objective: all
            action_gates: all
            PLANNING_runs: {}
          EXECUTION:
            status: off
            focused_pillars: all
            focused_objective: all
            action_gates: all
            EXECUTION_runs: {}
      INBOX:
        status: off
        gateway_delivery:
          status: off
          focused_pillars: all
        researches:
          status: off
          focused_pillars: all
          focused_objective: all
        runs:
          PLANNING:
            status: off
            focused_pillars: all
            focused_objective: all
            action_gates: all
            PLANNING_runs: {}
          EXECUTION:
            status: off