####################################################
# 
####################################################


dashboard: true | false

modes:

  system:
    status: true | false
    auto_mode: true | false

  pipeline-scaler:
    status: true | false
    auto_mode: true | false

  pipeline-hustler:
    status: true | false
    auto_mode: true | false

  project-assets_managment:
    status: true | false
    auto_mode: true | false

  project-darja_deals:
    status: true | false
    auto_mode: true | false

profiles:

  system:

    evolution:
      EXECUTION:
        status: true | false
      PLANNING:
        status: true | false

  pipeline-scaler:

    EXTERNAL:
      EXECUTION:
        status: true | false
        pillars: Foundational_Integrity, Operational_Muscles, Value_Generation
        action_gate: inject_into_existing, build_new_component, extend_existing_system,
          replace_or_upgrade, restructure_architecture, migrate_and_reposition
      PLANNING:
        status: true | false
        pillars: Foundational_Integrity, Operational_Muscles, Value_Generation
        action_gate: inject_into_existing, build_new_component, extend_existing_system,
          replace_or_upgrade, restructure_architecture, migrate_and_reposition
      
    INTERNAL:
      EXECUTION:
        status: true | false
        pillars: Foundational_Integrity, Operational_Muscles, Value_Generation
        action_gate: patch_file enrich_file replace_schema restructure_system
      PLANNING:
        status: true | false
        pillars: Foundational_Integrity, Operational_Muscles, Value_Generation
        action_gate: patch_file enrich_file replace_schema restructure_system
    
  pipeline-hustler:
      
    INGESTION:
      EXECUTION:
        status: true | false
        action_gate: cascade_into_existing_feature, cascade_into_existing_product, validate_new_feature,
          validate_new_product, validate_new_focus, cluster_first_audit
      PLANNING:
        status: true | false
        action_gate: cascade_into_existing_feature, cascade_into_existing_product, validate_new_feature,
          validate_new_product, validate_new_focus, cluster_first_audit
    
    PROCESSING:
      EXECUTION:
        status: true | false
        action_gate: definition_extraction, tag_transition_new_data_to_processed, extract_need_from_processed_data,
          scrape_for_data_gap, productization_marking
      PLANNING:
        status: true | false
        action_gate: definition_extraction, tag_transition_new_data_to_processed, extract_need_from_processed_data,
          scrape_for_data_gap, productization_marking

  project-assets_managment:

    EXECUTION:
      status: true | false
    PLANNING:
      status: true | false

  project-darja_deals:

    EXECUTION:
      status: true | false
    PLANNING:
      status: true | false


####################################################
# 
####################################################